export const states = [
  { name: "Punjab", abbreviation: "PB" },
  { name: "Rajasthan", abbreviation: "RJ" },
  { name: "Madhya Pradesh", abbreviation: "MP" },
  { name: "Uttar Pradesh", abbreviation: "UP" },
  { name: "Tripura", abbreviation: "TR" },
  { name: "Kerala", abbreviation: "KL" },
  { name: "Delhi", abbreviation: "DL" },
  { name: "West Bengal", abbreviation: "WB" },
  { name: "Goa", abbreviation: "GA" },
  { name: "Himachal Pradesh", abbreviation: "HP" },
  { name: "Karnataka", abbreviation: "KA" },
  { name: "Meghalaya", abbreviation: "ML" },
  { name: "Nagaland", abbreviation: "NL" },
  { name: "Bihar", abbreviation: "BR" },
  { name: "Puducherry", abbreviation: "PY" },
  { name: "Chattisgarh", abbreviation: "CG" },
  { name: "Sikkim", abbreviation: "SK" },
  { name: "Arunachal Pradesh", abbreviation: "AR" },
  { name: "Jharkhand", abbreviation: "JH" },
  { name: "Hariyana", abbreviation: "HR" },
  { name: "Manipur", abbreviation: "MN" },
  { name: "Mizoram", abbreviation: "MZ" },
  { name: "Orisha", abbreviation: "OR" },
  { name: "Assam", abbreviation: "AS" },
  { name: "Jammu and Kashmir", abbreviation: "JK" },
  { name: "Tamil Nadu", abbreviation: "TN" },
  { name: "Uttarakhand", abbreviation: "UK" },
  { name: "Telengana", abbreviation: "TS" },
  { name: "Gujarat", abbreviation: "GJ" },
  { name: "Maharashtra", abbreviation: "MH" },
  { name: "Andhra Pradesh", abbreviation: "AP" },
];

export const categories = [
  { name: "OPEN", value: "OPEN" },
  { name: "EWS", value: "EWS" },
  { name: "OBC-NCL", value: "OBC-NCL" },
  { name: "SC", value: "SC" },
  { name: "ST", value: "ST" },
  { name: "OPEN (PwD)", value: "OPEN (PwD)" },
  { name: "EWS (PwD)", value: "EWS (PwD)" },
  { name: "SC (PwD)", value: "SC (PwD)" },
  { name: "OBC-NCL (PwD)", value: "OBC-NCL (PwD)" },
  { name: "ST (PwD)", value: "ST (PwD)" },
];
